# Generated by Django 3.1.4 on 2021-02-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='identity',
        ),
    ]
