# Generated by Django 3.1.4 on 2021-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CAPEX',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Productivity',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
