# Generated by Django 3.1.4 on 2021-02-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Cluster',
            field=models.CharField(blank=True, choices=[('MTS-MTO', 'MTS-MTO'), ('MTOMTS', 'MTOMTS'), ('MTO-CTO', 'MTO-CTO'), ('MTS-CTO', 'MTS-CTO'), ('ETO-MV', 'ETO-MV'), ('NA', 'NA')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Current_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Deployment', 'Deployment'), ('Produce', 'Produce'), ('Closed', 'Closed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_leader',
            field=models.CharField(blank=True, choices=[('Caiqin LI', 'Caiqin LI'), ('Chenghai WANG', 'Chenghai WANG'), ('Fiona ZHANG', 'Fiona ZHANG'), ('Hui FENG', 'Hui FENG'), ('HuLin-Alex Cai', 'HuLin-Alex Cai'), ('Karen', 'Karen'), ('Kathyn Ye', 'Kathyn Ye'), ('KOU Lifang', 'KOU Lifang'), ('LI Ang', 'LI Ang'), ('LIU Hui', 'LIU Hui'), ('Luo Wei', 'Luo Wei'), ('MAO Haixing', 'MAO Haixing'), ('Mark Yu', 'Mark Yu'), ('Mike ZHOU', 'Mike ZHOU'), ('Pan Wen', 'Pan Wen'), ('Pending', 'Pending'), ('Qihui Zhou', 'Qihui Zhou'), ('Quanguo-Michael Li', 'Quanguo-Michael Li'), ('Sheng BI', 'Sheng BI'), ('Shengjie SHEN', 'Shengjie SHEN'), ('SUN Xiaodong', 'SUN Xiaodong'), ('Tony LU', 'Tony LU'), ('Weiwei-Eric Zhang', 'Weiwei-Eric Zhang'), ('Xi ming', 'Xi ming'), ('Xinye LUO', 'Xinye LUO'), ('Yiping-Patrick.Feng', 'Yiping-Patrick.Feng'), ('YuE-Peggy Zhu', 'YuE-Peggy Zhu'), ('ZHANG Chunxin', 'ZHANG Chunxin'), ('ZHANG Na', 'ZHANG Na'), ('Songyang XU', 'Songyang XU'), ('NA', 'NA')], max_length=30, null=True),
        ),
    ]
