# Generated by Django 3.1.4 on 2021-01-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0002_auto_20210103_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Target_MP_date',
            new_name='Produce_date',
        ),
        migrations.AddField(
            model_name='project',
            name='Region',
            field=models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East&West', 'East&West'), ('Wuxi', 'Wuxi')], default='No region', max_length=30),
        ),
    ]
