# Generated by Django 3.1.4 on 2021-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0003_auto_20210317_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Do_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='IMP_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Sell_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
