# Generated by Django 3.1.4 on 2021-03-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0004_auto_20210317_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Complexity',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Project_name',
            field=models.CharField(max_length=100),
        ),
    ]
