# Generated by Django 3.1.4 on 2021-01-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0005_auto_20210107_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Space_needed',
            field=models.FloatField(blank=True, null=True, verbose_name='Space needed'),
        ),
    ]
