# Generated by Django 3.1.4 on 2021-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0006_auto_20210318_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='Summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='BU',
            field=models.CharField(blank=True, choices=[('Digital Energy', 'Digital Energy'), ('Home & Distribution', 'Home & Distribution'), ('Industrial & Automation', 'Industrial & Automation'), ('PP', 'Power Products'), ('PS', 'Power System Primary'), ('Power System Secondary', 'Power System Secondary'), ('SP', 'Secure Power'), ('ALL', 'ALL'), ('NA', 'NA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Cluster',
            field=models.CharField(blank=True, choices=[('MTS-MTO', 'MTS-MTO'), ('MTO-CTO', 'MTO-CTO'), ('MTS-CTO', 'MTS-CTO'), ('ETO-MV', 'ETO-MV'), ('NA', 'NA')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Complexity',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Current_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Do', 'Do'), ('IMP', 'IMP'), ('Produce', 'Produce'), ('Sell', 'Sell'), ('Closed', 'Closed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Lob',
            field=models.CharField(blank=True, choices=[('DBPRD', 'DBPRD'), ('DPENP', 'DPENP'), ('DPSOL', 'DPSOL'), ('IDEUR', 'IDEUR'), ('IDHMI', 'IDHMI'), ('IDMST', 'IDMST'), ('IDSDS', 'IDSDS'), ('IDSIG', 'IDSIG'), ('IDVSD', 'IDVSD'), ('IDWDA', 'IDWDA'), ('INMCP', 'INMCP'), ('INMVE', 'INMVE'), ('INMVP', 'INMVP'), ('PTACB', 'PTACB'), ('PTCCB', 'PTCCB'), ('PTCTR', 'PTCTR'), ('PTEQP', 'PTEQP'), ('PTFDA', 'PTFDA'), ('PTFDB', 'PTFDB'), ('PTLTVB', 'PTLTVB'), ('PTSOL', 'PTSOL'), ('PTWDA', 'PTWDA'), ('SP3PH', 'SP3PH'), ('SPMDC', 'SPMDC'), ('HDFDB', 'HDFDB'), ('ALL', 'ALL'), ('NA', 'NA')], max_length=30, null=True),
        ),
    ]
