# Generated by Django 3.1.4 on 2021-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0007_auto_20210326_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='Picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
