# Generated by Django 3.1.4 on 2021-03-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0008_auto_20210327_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='Picture',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
