# Generated by Django 3.1.4 on 2021-03-29 01:25

import PM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0009_auto_20210327_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='Picture',
            field=models.ImageField(null=True, upload_to=PM.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='Summary',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
