# Generated by Django 3.1.4 on 2021-04-07 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PM', '0010_auto_20210329_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='Lob',
            field=models.CharField(blank=True, choices=[('DBPRD', 'DBPRD'), ('DPENP', 'DPENP'), ('DPSOL', 'DPSOL'), ('IDEUR', 'IDEUR'), ('IDHMI', 'IDHMI'), ('IDMST', 'IDMST'), ('IDSDS', 'IDSDS'), ('IDSIG', 'IDSIG'), ('IDVSD', 'IDVSD'), ('IDWDA', 'IDWDA'), ('INMCP', 'INMCP'), ('INMVE', 'INMVE'), ('INMVP', 'INMVP'), ('PTACB', 'PTACB'), ('PTCCB', 'PTCCB'), ('PPCTR', 'PPCTR'), ('PTEQP', 'PTEQP'), ('PTFDA', 'PTFDA'), ('PTFDB', 'PTFDB'), ('PTLTVB', 'PTLTVB'), ('PTSOL', 'PTSOL'), ('PTWDA', 'PTWDA'), ('SP3PH', 'SP3PH'), ('SPMDC', 'SPMDC'), ('HDFDB', 'HDFDB'), ('ALL', 'ALL'), ('NA', 'NA')], max_length=30, null=True),
        ),
    ]
